#!/usr/bin/env python

# tailosd - Tail files with On Screen Display output

# Copyright (c) 2014,2016 Laurent Ghigonis <laurent@gouloum.fr>
# Copyright (c) 2014,2015 Pierre-Olivier Vauboin <povauboin@gmail.com>

import os
import sys
import argparse
import signal
import getpass

import tailosd

_w = None
USER = getpass.getuser()
PIDFILE = "/var/tmp/tailosd_%s.pid" % USER

def _sigint(signal, frame):
    print('ctrl-c, exiting')
    os.remove(PIDFILE)
    sys.exit(0)
def _sighup(signal, frame):
    print('sighup, reloading filters')
    _w.reload_conf()
def _sigusr1(signal, frame):
    print('sigusr1, pausing')
    _w.pause()
def _sigusr2(signal, frame):
    print('sigusr2, resuming')
    _w.resume()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Tail files with On Screen Display output')
    parser.add_argument('-d', dest='debug', action='store_true',
                        help='Debug mode')
    parser.add_argument('-f', dest='config_file',
                        help='Configuration file for severity filters and colors')
    parser.add_argument('-p', dest='pause', action='store_true',
                        help='Trigger pause of OSD display in running instance')
    parser.add_argument('-P', dest='resume', action='store_true',
                        help='Trigger resume of OSD display in running instance')
    parser.add_argument('-r', dest='reload', action='store_true',
                        help='Trigger reload of configuration in running instance')
    parser.add_argument('-l', dest='loglevel', choices=tailosd.SEVERITY_CHOICES,
                        help='Log level [default=%s]' % tailosd.SEVERITY_DEFAULT)
    parser.add_argument('target', nargs='*',
                        help='File paths to monitor | systemd')
    args = parser.parse_args()

    if args.reload or args.pause or args.resume:
        if not os.path.exists(PIDFILE):
            parser.error("PID file does not exist, is tailosd running under same user \"%s\" ? (%s)" % (USER, PIDFILE))
        with open(PIDFILE) as f:
            pid = int(f.read())
            if args.reload: os.kill(pid, signal.SIGHUP)
            if args.pause: os.kill(pid, signal.SIGUSR1)
            if args.resume: os.kill(pid, signal.SIGUSR2)
        print("signal sent to running tailosd")
        sys.exit(0)

    target = dict()
    for t in args.target:
        if t == "systemd":
            if "files" in target:
                parser.error("Cannot use 'systemd' together with files")
            target["systemd"] = True
        else:
            if "systemd" in target:
                parser.error("Cannot use files together with systemd")
            if not os.path.isfile(t):
                parser.error("File does not exist : %s" % t)
            if not os.access(t, os.R_OK):
                parser.error("File not readable : %s" % t)
            if "files" not in target:
                target["files"] = list()
            target["files"].append(t)
    if len(target) == 0:
        parser.error("You have to specify a target or a trigger action")

    if args.loglevel:
        loglevel = args.loglevel
    elif 'TAILOSD_LOGLEVEL' in os.environ:
        loglev = os.environ.get('TAILOSD_LOGLEVEL')
    else:
        loglevel = tailosd.SEVERITY_DEFAULT
    if loglevel not in tailosd.SEVERITY_CHOICES:
        parser.error("Invalid log level %s, valid choices are : %s" % (loglevel, tailosd.SEVERITY_CHOICES))
    loglevel = tailosd.SEVERITY_CHOICES[loglevel]

    with open(PIDFILE, 'w') as f:
        f.write('%d' % os.getpid())
    signal.signal(signal.SIGINT, _sigint)
    signal.signal(signal.SIGHUP, _sighup)
    signal.signal(signal.SIGUSR1, _sigusr1)
    signal.signal(signal.SIGUSR2, _sigusr2)

    _w = tailosd.Tailosd(target, args.config_file, loglevel, args.debug)
    _w.run()
